export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense'

/**
 * Second-level classification within a type, driving how the account is grouped and
 * subtotalled on the Balance Sheet and Profit & Loss.
 *
 * - Assets split into current (cash, bank, AR, inventory, prepayments) and fixed
 *   (land, buildings, equipment, vehicles, and accumulated depreciation).
 * - Liabilities split by tenor into current (AP, accruals, tax payable, short-term
 *   loans) and long-term (long-term loans, mortgages). The same *kind* of account
 *   can fall either side, so this is a user-set property — never inferred at report time.
 * - Expenses split into cost of sales (presented above the Gross Profit line) and
 *   operating expenses (below it).
 *
 * Equity and revenue accounts have no subtype.
 *
 * Optional on the record: accounts created before this field existed carry no value.
 * Reports must resolve them through `resolveSubtype()` (see utils/accountClassification)
 * rather than reading `subtype` directly, so legacy accounts never drop out of a total.
 */
export type AccountSubtype =
  | 'current_asset'
  | 'fixed_asset'
  | 'current_liability'
  | 'long_term_liability'
  | 'cost_of_sales'
  | 'operating_expense'

/**
 * Tags a control/system account so the posting engine can resolve it by role
 * (e.g. "the AR account") regardless of its code/name. Undefined for ordinary accounts.
 */
export type SystemAccountType =
  | 'accounts_receivable'
  | 'accounts_payable'
  | 'tax_payable'
  | 'retained_earnings'
  | 'opening_balance_equity'
  | 'sales'          // default income account for invoice lines
  | 'purchases'      // default expense account for bill lines
  | 'bank'           // default cash/bank account
  | 'exchange_gain_loss'
  | 'inventory'      // stock asset account (perpetual inventory)
  | 'cogs'           // cost of goods sold (posted on inventory sales)

export interface Account {
  id: string
  code: string
  name: string
  type: AccountType
  subtype?: AccountSubtype | null
  parentId: string | null
  currency: string
  isActive: boolean
  balance: number
  description: string
  systemType?: SystemAccountType | null
  createdAt: Date
  updatedAt: Date
}

export interface JournalLine {
  accountId: string
  accountName?: string
  debit: number
  credit: number
  description: string
}

export type JournalStatus = 'draft' | 'posted' | 'reversed'

export interface JournalEntry {
  id: string
  date: Date
  reference: string
  memo: string
  lines: JournalLine[]
  status: JournalStatus
  createdBy: string
  createdAt: Date
  updatedAt: Date
  /**
   * True when this entry was generated by the server-side posting engine from a
   * subledger document (invoice, bill, receipt, payment, bank transaction). Such
   * entries are system-owned and must not be manually edited, deleted, or reversed —
   * change the source document instead and the engine re-posts.
   */
  autoPosted?: boolean
  source?: { type: string; id: string } | null
}

export interface LedgerEntry {
  date: Date
  reference: string
  description: string
  debit: number
  credit: number
  balance: number
  journalEntryId: string
}

export interface TrialBalanceRow {
  accountId: string
  accountCode: string
  accountName: string
  accountType: AccountType
  debit: number
  credit: number
}
